django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from post import views as post_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # post앱의 index뷰를 root url에 연결시킨다.
    # url(r'^$', post_views.index),

    # post앱의 urls.py모듈을 include시킨다
    url(r'^post/', include('post.urls')),

    url(r'^member/', include('member.urls')),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_app/member/urls.py
from django.conf.urls import url
from . import views

app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

django_app/post/urls.py
from django.conf.urls import url
from . import views

# URL Namespace
# https://docs.djangoproject.com/en/1.11/topics/http/urls/#url-namespaces
app_name = 'post'
urlpatterns = [
    # url() 사용법
    # https://docs.djangoproject.com/en/1.11/ref/urls/#url

    # post_list와 매칭
    # /post/$
    url(r'^$', views.post_list, name='post_list'),

    # post_detail과 매칭
    # /post/3/$, /post/35/$
    # 정규표현식에서 매칭된 그룹을 위치인수로 반환하는 방법
    # url(r'^(\d+)/$', views.post_detail),

    # 정규표현식에서 매칭된 그룹을 키워드인수로 반환하는 방법
    # 그룹의 가장 앞 부분에 ?P<패턴이름>을 지정
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),

    # post_create와 매칭
    url(r'^create/$', views.post_create, name='post_create'),

    # 위쪽의 결과들과 매칭되지 않을 경우
    url(r'^.*/$', views.post_anyway, name='post_anyway'),
]

django_app/templates/common/base.html
{% load static %}
<!--
	템플릿 상속
		https://docs.djangoproject.com/en/1.11/ref/templates/language/#template-inheritance

	static 태그
		https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#static
-->
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <title>Instagram</title>
</head>
<body>
<div id="wrap">
    <header class="top-header">
        <nav>
            <div class="nav-left nav-item">
                <a href="{% url 'post:post_list' %}">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </a>
            </div>
            <div class="nav-center nav-item">
                <input type="text" placeholder="검색">
            </div>
            <div class="nav-right nav-item">
                <a href="#">
                    <img src="{% static 'images/icon_explore.png' %}" alt="">
                </a>
                <a href="#">
                    <img src="{% static 'images/icon_heart.png' %}" alt="">
                </a>
                <a href="#">
                    <img src="{% static 'images/icon_profile.png' %}" alt="">
                </a>
            </div>
        </nav>
        <nav>
            <div>
                {% if user.is_authenticated %}
                <span>Hello {{ user }}!</span>
                <a href="{% url 'member:logout' %}" class="btn">Logout</a>
                {% else %}
                <a href="{% url 'member:login' %}" class="btn">Login</a>
                <a href="{% url 'member:signup' %}" class="btn">Signup</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>